Number of super categories: 10
Number of categories: 10
Number of annotations: 26240
Number of images: 3272
loading annotations into memory...
Done (t=4.13s)
creating index...
index created!
loading annotations into memory...
Done (t=0.90s)
creating index...
index created!
loading annotations into memory...
Done (t=0.02s)
creating index...
index created!
image shape: [3, 512, 512]
mask shape:  [512, 512]
Unique values, category of transformed mask :
 [{0, 'Backgroud'}, {2, 'Paper'}, {8, 'Plastic bag'}]
image shape: [3, 512, 512]
mask shape:  [512, 512]
Unique values, category of transformed mask :
 [{0, 'Backgroud'}, {5, 'Glass'}, {'Plastic', 6}, {8, 'Plastic bag'}]
image shape: [3, 512, 512]
input shape : torch.Size([2, 3, 512, 512])
output shape : torch.Size([2, 11, 512, 512])
Start training..
Epoch [1/100], Step [25/219],                         Loss: 1.2375, mIoU: 0.1579
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f545f6fed40>
Traceback (most recent call last):
  File "/opt/conda/envs/segmentation/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in __del__
    self._shutdown_workers()
  File "/opt/conda/envs/segmentation/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1177, in _shutdown_workers
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/opt/conda/envs/segmentation/lib/python3.7/multiprocessing/process.py", line 140, in join
    res = self._popen.wait(timeout)
  File "/opt/conda/envs/segmentation/lib/python3.7/multiprocessing/popen_fork.py", line 45, in wait
    if not wait([self.sentinel], timeout):
  File "/opt/conda/envs/segmentation/lib/python3.7/multiprocessing/connection.py", line 921, in wait
    ready = selector.select(timeout)
  File "/opt/conda/envs/segmentation/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt:
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.
Traceback (most recent call last):
  File "/opt/conda/envs/segmentation/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_25491/295132338.py", line 1, in <module>
    train(num_epochs, model, train_loader, val_loader, criterion, optimizer, saved_dir, val_every, device)
  File "/tmp/ipykernel_25491/1356911439.py", line 33, in train
    optimizer.zero_grad()
  File "/opt/conda/envs/segmentation/lib/python3.7/site-packages/torch/optim/optimizer.py", line 192, in zero_grad
    p.grad.zero_()
KeyboardInterrupt
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/conda/envs/segmentation/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2064, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/conda/envs/segmentation/lib/python3.7/site-packages/IPython/core/ultratb.py", line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/opt/conda/envs/segmentation/lib/python3.7/site-packages/IPython/core/ultratb.py", line 248, in wrapped
    return f(*args, **kwargs)
  File "/opt/conda/envs/segmentation/lib/python3.7/site-packages/IPython/core/ultratb.py", line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/opt/conda/envs/segmentation/lib/python3.7/inspect.py", line 1502, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "/opt/conda/envs/segmentation/lib/python3.7/inspect.py", line 1460, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "/opt/conda/envs/segmentation/lib/python3.7/inspect.py", line 696, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "/opt/conda/envs/segmentation/lib/python3.7/inspect.py", line 742, in getmodule
    os.path.realpath(f)] = module.__name__
  File "/opt/conda/envs/segmentation/lib/python3.7/posixpath.py", line 395, in realpath
    path, ok = _joinrealpath(filename[:0], filename, {})
  File "/opt/conda/envs/segmentation/lib/python3.7/posixpath.py", line 428, in _joinrealpath
    newpath = join(path, name)
  File "/opt/conda/envs/segmentation/lib/python3.7/posixpath.py", line 89, in join
    elif not path or path.endswith(sep):
KeyboardInterrupt
Process wandb_internal:
Traceback (most recent call last):
  File "/opt/conda/envs/segmentation/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/opt/conda/envs/segmentation/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/segmentation/lib/python3.7/site-packages/wandb/sdk/internal/internal.py", line 152, in wandb_internal
    thread.join()
  File "/opt/conda/envs/segmentation/lib/python3.7/threading.py", line 1044, in join
    self._wait_for_tstate_lock()
  File "/opt/conda/envs/segmentation/lib/python3.7/threading.py", line 1060, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/envs/segmentation/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/opt/conda/envs/segmentation/lib/python3.7/multiprocessing/spawn.py", line 118, in _main
    return self._bootstrap()
  File "/opt/conda/envs/segmentation/lib/python3.7/multiprocessing/process.py", line 315, in _bootstrap
    threading._shutdown()
  File "/opt/conda/envs/segmentation/lib/python3.7/threading.py", line 1307, in _shutdown
    lock.acquire()
KeyboardInterrupt